package domain

import "errors"

var (
	ErrRoomNotFound               = errors.New("room not found")
	ErrSlotNotFound               = errors.New("slot not found")
	ErrSlotAlreadyBooked          = errors.New("slot is already booked")
	ErrBookingNotFound            = errors.New("booking not found")
	ErrScheduleExists             = errors.New("schedule for this room already exists")
	ErrInvalidTime                = errors.New("invalid time provided")
	ErrForbidden                  = errors.New("forbidden")
	ErrUnauthorized               = errors.New("unauthorized")
	ErrEmailExists                = errors.New("email already exists")
	ErrInvalidCredentials         = errors.New("invalid credentials")
	ErrCityNotFound               = errors.New("city not found")
	ErrHubNotFound                = errors.New("hub not found")
	ErrMentorNotFound             = errors.New("mentor not found")
	ErrSkillNotFound              = errors.New("skill not found")
	ErrMentorRequestNotFound      = errors.New("mentor request not found")
	ErrConflict                   = errors.New("conflict")
	ErrInvalidInput               = errors.New("invalid input")
	ErrAlreadyExists              = errors.New("already exists")
	ErrBookingCapacityExceeded    = errors.New("booking capacity exceeded")
	ErrBookingTimeConflict        = errors.New("booking time conflict")
	ErrBookingCityMismatch        = errors.New("booking city mismatch")
	ErrSlotTimeConflict           = errors.New("slot time conflict")
	ErrRoomAvailabilityConflict   = errors.New("room availability conflict")
	ErrMentorAvailabilityConflict = errors.New("mentor availability conflict")
)
